#!groovy
def repoName = GIT_URL.tokenize('/').last().split("\\.")[0]
pipeline {
    agent {
        docker {
            image 'nestjs/cli:latest'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage ('Prepare'){
            steps{
                script {
                    sh 'npm run install'

                }
            }
        }
        stage ('Test'){
            steps{
                script {
                    sh 'npm run test'

                }
            }
        }
        stage ('Docker'){
            when {
                environment name: 'GIT_BRANCH', value: 'master'
            }
            steps{
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]){
                        sh 'docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}'
                    }
                    def imageName = 'jabrego/'+repoName+':${GIT_COMMIT}'
                    def imageNameLatest = 'jabrego/'+repoName+':latest'
                    sh 'docker build -t '+imageName+' .'
                    sh 'docker tag '+imageName+' '+imageNameLatest
                    sh 'docker push '+imageName
                    sh 'docker push '+imageNameLatest
                }
            }
        }
        stage ('Deploy'){
            when {
                environment name: 'GIT_BRANCH', value: 'master'
            }
            steps{
                script {
                    k8s.deploy(repoName, GIT_COMMIT)
                }
            }
        }
    }
}
